# Generated by Django 3.1 on 2020-09-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college_address',
            field=models.CharField(default='andheri,mumbai', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='college_name',
            field=models.CharField(default='spit', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='usermobile',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
