# Generated by Django 3.1 on 2020-09-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200912_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_type',
            old_name='book_id',
            new_name='book',
        ),
    ]
