# Generated by Django 3.1 on 2020-09-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200923_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_book',
            old_name='needs-book',
            new_name='needs_book',
        ),
        migrations.RenameField(
            model_name='request_book',
            old_name='to-user',
            new_name='to_user',
        ),
    ]
