# Generated by Django 3.1 on 2020-09-28 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0009_auto_20200923_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request_book',
            unique_together={('to_user', 'needs_book')},
        ),
    ]
